### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by fuzzy76** [estum/Google-Image-Search-safariextension#1]
Did you remove the download? I can't find any other extensions for Safari with this functionality. :-/

**Comment by estum** [comment]
@fuzzy76 [Download "Google Search by Image.safariextz"](https://github.com/downloads/estum/Google-Image-Search-safariextension/Google%20Search%20by%20Image.safariextz)

**Comment by fuzzy76** [comment]
Thanks. :) Seems like Github has retired the old "downloads" functionality, but the links still work.
